name: test
on: 
  push:
  issue_comment:
    types: [created, edited]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: philips-labs/nostradamus-js-action@main
      id: nostradamus
      with:
        sourcePath: .
    - run: |
        echo "has new dependencies:"
        echo ${steps.nostradamus.outputs.newDependencies}
