name: test
on: 
  push:
  issue_comment:
    types: [created, edited]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: philips-labs/nostradamus-js-action@main
      id: nostradamus
      with:
        sourcePath: .
    - name: cat output
      run: echo "newDependencies: ${{ steps.nostradamus.outputs.newDependencies }}
